---
name: Docker Build/Publish Image

on:
  push:
    branches: [production]
    paths-ignore:
      - README.md
      - .trunk
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Login to DockerHub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get current date
        run: echo "DATE=$(date +'%Y.%m.%d')" >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:${{ env.DATE }}-${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64

      - name: Create a Release
        uses: elgohr/Github-Release-Action@3af318c9bb451e43ab8cea7fa17a5598abe94ed2 # 20240816194204
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Release ${{ env.DATE }}"

      - name: Send Discord notification
        uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708 # v1
        if: always()
        with:
          title: "Build image on ${{ github.repository }}: ${{ github.workflow }}"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
